### ISSUE TITLE
Hyperlinks.

### ISSUE THREAD

**Issue by YehiaWLD** [Abdelrahmanthecoder/Abdelrahmanthecoder.portfolio.github.io#1]
Change website links to hyperlinks so we can actually click on them!! no one will copy paste it into their browser

**Comment by YehiaWLD** [comment]
@Abdelrahmanthecoder

**Comment by Abdelrahmanthecoder** [comment]
I'm working to fix this problem as soon as possible!

**Comment by Abdelrahmanthecoder** [comment]
I have fixed the issue, thanks for the notice @YehiaWLD!
